name: Build and push image

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get branch name
        run: echo "REPOSITORY_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Run all
        run: |
          make build
          make test
          make push
        env:
          DOCKER_IMAGE: noxecane/aws-helm