name: Build and push image

on: push

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        run: echo "REPOSITORY_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        

      - name: Build image
        run: |
          make build
          make test
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: make push